### ISSUE TITLE
Wallet-Backend Error in Docker when doing Send payment

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#320]
On the Send page, whenever funds are sent to a payment pointer, the docker wallet-backend has on repeat an error that teher are not enough funds in that currency, even if that is not true:

[WebHookService] The request attempted an operation that requires funds in a specific currency, but there were not sufficient funds in that currency. The request was rejected. Corrective action: Transfer funds to the wallet in the required currency.
2023-04-28 11:38:51 [2023-04-28 08:38:51] [error] [GlobalErrorHandler] Unable to release amount 10 from ewallet_9552f107b67b826b93d6e415073ae6db
2023-04-28 11:38:51 Error: Unable to release amount 10 from ewallet_9552f107b67b826b93d6e415073ae6db
2023-04-28 11:38:51     at WebHookService.handleOutgoingPaymentCompleted (/home/testnet/packages/wallet-backend/dist/rafiki/integration/webhook/webhook.service.js:150:19)
2023-04-28 11:38:51     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-04-28 11:38:51     at async WebHookService.onWebHook (/home/testnet/packages/wallet-backend/dist/rafiki/integration/webhook/webhook.service.js:30:17)
2023-04-28 11:38:51     at async WebHookController.onWebHook (/home/testnet/packages/wallet-backend/dist/rafiki/integration/webhook/webhook.controller.js:10:17)

**Comment by Tymmmy** [comment]
Tested it again and there is no error happening for the time being.
Will keep an eye out, but for now we will close the issue
